language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose -c phpunit.xml
